[project]
name = "revolut-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uvicorn==0.38.0",
    "fastapi==0.120.4",
    "upstash-redis==1.5.0"
]